[tool.poetry]
name = "hierarch"
version = "1.1.4"
description = "Hierarchical hypothesis testing library"
authors = ["Rishi Kulkarni <rishi@kulkarni.science>"]
homepage = "https://github.com/rishi-kulkarni/hierarch"
license = "LICENSE.txt"
readme = "README.md"
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
    ]

[tool.poetry.dependencies]
python = ">=3.8.1, <3.12"
numba = "^0.57"
scipy = "^1.10.0"
pandas = ">=1.5.3,<3.0.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
flake8 = "^6.0.0"
pytest = "^7.2.1"
sphinx = "^6.1.3"
numpydoc = "^1.5.0"
sphinx-rtd-theme = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
